const artPieces = [
    {
        id: 1,
        title: "The Terminus",
        image: "/drawings/01_Chhatrapati_Shivaji_Terminus.jpg",
        isFeatured: true,
        featuredOrder: 18,
        thoughts: "School days. A building so grand it made a kid pick up a pencil and try. Every arch, every tower, every gothic detail felt like a challenge. I didn't know then that this was the beginning of something. I just wanted to get it right.",
    },
    {
        id: 2,
        title: "Ultron's Gaze",
        image: "/drawings/02_Detailed_Robot_Head_Study.jpg",
    },
    {
        id: 3,
        title: "Venice, One Point",
        image: "/drawings/03_Venice_Canal_Perspective.jpg",
    },
    {
        id: 4,
        title: "Autumn's Grin",
        image: "/drawings/04_Classic_Jack_O_Lantern.jpg",
    },
    {
        id: 5,
        title: "Crimson Bloom",
        image: "/drawings/05_Vibrant_Red_Hibiscus.jpg",
    },
    {
        id: 6,
        title: "Horns & Darkness",
        image: "/drawings/06_Horned_Skull_With_Keys.jpg",
        isFeatured: true,
        featuredOrder: 15,
        thoughts: "2020. Depression has its own aesthetic. Dark, ornate, a little dangerous. A skull crowned with horns and tentacles. I didn't plan it. It just came out of wherever I was.",
    },
    {
        id: 7,
        title: "Rising from Soil",
        image: "/drawings/07_Reaching_Zombie_Hand.jpg",
    },
    {
        id: 8,
        title: "My Father",
        image: "/drawings/08_Portrait_Man_With_Beard.jpg",
    },
    {
        id: 9,
        title: "Trakula Erupts",
        image: "/drawings/09_Volcano_Eruption_Silhouette.jpg",
    },
    {
        id: 10,
        title: "The Little Star Flower",
        image: "/drawings/10_Delicate_Pink_Star_Flower.jpg",
    },
    {
        id: 11,
        title: "Pen on Paper, 2019",
        image: "/drawings/11_Detailed_Pen_Sketch.jpg",
    },
    {
        id: 12,
        title: "My Mother",
        image: "/drawings/12_Portrait_Woman_With_Glasses.jpg",
    },
    {
        id: 13,
        title: "My Sister, Smiling",
        image: "/drawings/13_Smiling_Woman_Portrait_Sketch.jpg",
    },
    {
        id: 14,
        title: "The Weight of Thinking",
        image: "/drawings/14_Skull_With_Flowing_Tentacles.jpg",
        isFeatured: true,
        featuredOrder: 2,
        thoughts: "This is the last drawing I made before I became a programmer. The tentacles are not tentacles. They are thoughts. Every one of them pulling at something inside the skull. This was 2018, at its worst. I didn't have words for what I was feeling. So I drew this instead.",
    },
    {
        id: 15,
        title: "Out of the Dark",
        image: "/drawings/15_Train_Emerging_From_Tunnel.jpg",
        isFeatured: true,
        featuredOrder: 3,
        thoughts: "2024. The train is old, muddy, and still running. It doesn't know it's about to reach the light. It just keeps moving. That was me. Not fully out, not yet healed. But moving. That's where I first thought that maybe I'm better than who I think I am.",
    },
    {
        id: 16,
        title: "A Brush Made by a Brush",
        image: "/drawings/16_Realistic_Paintbrush_Study.jpg",
    },
    {
        id: 17,
        title: "When We Held On",
        image: "/drawings/17_Clasped_Hands_Gesture.jpg",
        isFeatured: true,
        featuredOrder: 16,
        thoughts: "2018. Two people holding hands. The third image in the hand series, and the warmest one. I drew what I felt. Wanting to be close, wanting it to last.",
    },
    {
        id: 18,
        title: "Don't Go",
        image: "/drawings/18_Shaded_Reaching_Hand_Study.jpg",
        isFeatured: true,
        featuredOrder: 17,
        thoughts: "Same era, different feeling. A hand stretched out. Not reaching for something, but trying to stop something from leaving. It was never a relationship. Just a crush. Maybe a first love. The simplest drawing with the strangest story.",
    },
    {
        id: 19,
        title: "Vasai Fort, Alone",
        image: "/drawings/19_Charminar_Sketch_Hyderabad.jpg",
        isFeatured: true,
        featuredOrder: 4,
        thoughts: "Late 2025, early 2026. I picked up the pencil again after years away. The church in Vasai Fort wasn't a subject. It was a mirror. Ruins still standing. Solitary but still there. That's what I was drawing.",
    },
    {
        id: 20,
        title: "Outside the Box",
        image: "/drawings/20_Gateway_Of_India_Sketch_Mumbai.jpg",
    },
    {
        id: 21,
        title: "Tic-Tac, 3D",
        image: "/drawings/21_Tic_Tac_Mixers_Still_Life.jpg",
    },
    {
        id: 22,
        title: "A Boat, A Lighthouse",
        image: "/drawings/22_Misty_Lake_And_Solitary_Boat.jpg",
    },
    {
        id: 23,
        title: "Deer at Night",
        image: "/drawings/23_Nocturnal_Forest_With_Deer_Silhouette.jpg",
    },
    {
        id: 24,
        title: "Warli Practice",
        image: "/drawings/24_Traditional_Warli_Folk_Art.jpg",
    },
    {
        id: 25,
        title: "Galaxy from a Spray Can",
        image: "/drawings/25_Cosmic_View_Galaxy_And_Planets.jpg",
    },
    {
        id: 26,
        title: "Collision Course",
        image: "/drawings/26_Celestial_Collision_Colorful_Space_Art.jpg",
    },
    {
        id: 27,
        title: "The Road Between Trees",
        image: "/drawings/27_Perspective_Path_Lined_With_Trees.jpg",
    },
    {
        id: 28,
        title: "Bridge Sketch",
        image: "/drawings/28_Lakeside_Dock_Pencil_Landscape.jpg",
    },
    {
        id: 29,
        title: "Same Bridge, in Color",
        image: "/drawings/29_Lakeside_Dock_Watercolor_Landscape.jpg",
    },
    {
        id: 30,
        title: "The Lake in Winter",
        image: "/drawings/30_Winter_Lake_And_Bare_Trees.jpg",
    },
    {
        id: 31,
        title: "I Am Iron Man",
        image: "/drawings/31_Iron_Man_Iconic_Quote.jpg",
    },
    {
        id: 32,
        title: "I Can Do This All Day",
        image: "/drawings/32_Captain_America_Endurance_Quote.jpg",
    },
    {
        id: 33,
        title: "God of Thunder",
        image: "/drawings/33_Thor_God_Of_Thunder_Quote.jpg",
    },
    {
        id: 34,
        title: "Pointy Waves",
        image: "/drawings/34_Stormy_Seas_And_Boat_Sketch.jpg",
    },
    {
        id: 35,
        title: "Shading a Coconut",
        image: "/drawings/35_Assorted_Vegetables_And_Fruit_Study.jpg",
    },
    {
        id: 36,
        title: "She Had Glasses",
        image: "/drawings/36_Woman_With_Sunglasses_Profile_Sketch.jpg",
        isFeatured: true,
        featuredOrder: 12,
        thoughts: "College era. I was still in that familiar fog. A different person this time, not the first love, but real enough. The glasses aren't a detail. They're a disguise. I painted her without painting her.",
    },
    {
        id: 37,
        title: "Spirals in Black",
        image: "/drawings/37_Abstract_Noire_Et_Blanc_Spirals.jpg",
    },
    {
        id: 38,
        title: "Eagle, Abstract",
        image: "/drawings/38_Patriotic_Eagle_Star_Composition.jpg",
    },
    {
        id: 39,
        title: "Color Grid Experiment",
        image: "/drawings/39_Primary_Color_Conundrum.jpg",
    },
    {
        id: 40,
        title: "Geometric Fragments",
        image: "/drawings/40_Fragmented_Rainbow_Shards.jpg",
    },
    {
        id: 41,
        title: "A Saree Pattern",
        image: "/drawings/41_Ornate_Teal_Textile_Pattern.jpg",
    },
    {
        id: 42,
        title: "Violet Mandala",
        image: "/drawings/42_Purple_And_Gold_Floral_Mandala.jpg",
    },
    {
        id: 43,
        title: "Warm Butterfly Bloom",
        image: "/drawings/43_Symmetrical_Butterfly_Bloom_Mandala.jpg",
    },
    {
        id: 44,
        title: "Decorative Fan",
        image: "/drawings/44_Decorative_Hand_Fan_Floral_Design.jpg",
    },
    {
        id: 45,
        title: "The Lamp",
        image: "/drawings/45_Aquatic_Floral_Lampshade_Fantasy.jpg",
    },
    {
        id: 46,
        title: "A Bad One",
        image: "/drawings/46_Tribal_Inspired_Fish_Graphic.jpg",
    },
    {
        id: 47,
        title: "Cat Watching the Blast",
        image: "/drawings/47_Moonlit_Silhouette_Cat_On_Fence.jpg",
    },
    {
        id: 48,
        title: "When I Was Happy",
        image: "/drawings/48_Pensive_Man_In_Blue_Watercolor.jpg",
        isFeatured: true,
        featuredOrder: 11,
        thoughts: "Late 2025, early 2026. Small drawing. Lots of color. That's how I knew things were different. I actually wanted color. I made this when I was happy and couldn't quite explain why. Still can't.",
    },
    {
        id: 49,
        title: "Bamboo Wreath",
        image: "/drawings/49_Bamboo_And_Leaf_Handicraft_Wreath.jpg",
    },
    {
        id: 50,
        title: "Color Chaos",
        image: "/drawings/50_Impasto_Chromatic_Explosion.jpg",
    },
    {
        id: 51,
        title: "Tropical Tee Design",
        image: "/drawings/51_Tropical_Island_Beach_TShirt_Art.jpg",
    },
    {
        id: 52,
        title: "Everything in the Sky",
        image: "/drawings/52_Journey_Through_The_Skies_And_Space.jpg",
    },
    {
        id: 53,
        title: "Save Farmers",
        image: "/drawings/53_Farmers_Life_Illustrated_Typography.jpg",
    },
    {
        id: 54,
        title: "Lines & Lines",
        image: "/drawings/54_Street_Scene_Covid_Sanitization_Effort.jpg",
    },
    {
        id: 55,
        title: "Practice Sketch",
        image: "/drawings/55_Vibrant_Indian_Railway_Station_Scene.jpg",
    },
    {
        id: 56,
        title: "Covid Era",
        image: "/drawings/56_Optical_Gradient_Chevron_Waves.jpg",
    },
    {
        id: 57,
        title: "Me & the Sunflower",
        image: "/drawings/57_Daydreaming_In_A_Sunflower_Field.jpg",
    },
    {
        id: 58,
        title: "Holi",
        image: "/drawings/58_Joyful_Holi_Festival_Colors.jpg",
    },
    {
        id: 59,
        title: "School Era Abstract",
        image: "/drawings/59_Abstract_Carnival_Of_Shapes.jpg",
    },
    {
        id: 60,
        title: "This is What Music Feels Like",
        image: "/drawings/60_Psychedelic_Soundwaves_Aura.jpg",
        isFeatured: true,
        featuredOrder: 7,
        thoughts: "I couldn't describe it in words, so I drew it. Music doesn't just play. It lifts something. A quiet confidence, a sudden warmth. This is what it looks like from the inside.",
    },
    {
        id: 61,
        title: "School Abstract",
        image: "/drawings/61_Fluid_Forms_Of_Rainbow_Creature.jpg",
    },
    {
        id: 62,
        title: "Sunflower Dish",
        image: "/drawings/62_Sunflower_And_Vine_Roundel_Design.jpg",
    },
    {
        id: 63,
        title: "Save Trees",
        image: "/drawings/63_Eco_Message_Against_Deforestation_Art.jpg",
    },
    {
        id: 64,
        title: "Rain & Lamplight",
        image: "/drawings/64_Girl_in_rain_Wet_lamp_post.jpg",
        isFeatured: true,
        featuredOrder: 19,
        thoughts: "2024, internship era. Rain has a way of making everything feel more honest. She's standing in it, not running from it. The lamp beside her is the only warm thing in the frame. There's something quietly brave about someone who lets themselves get rained on.",
    },
    {
        id: 65,
        title: "Those Eyes",
        image: "/drawings/65_Women_Closeup.jpg",
        isFeatured: true,
        featuredOrder: 6,
        thoughts: "Made in late 2025, but the memory is from school. This is what she looked like. Not exactly. I can't replicate something that felt like that. But this is close enough to make me remember.",
    },
    {
        id: 66,
        title: "Nana Patekar",
        image: "/drawings/66_Nana.jpg",
    },
    {
        id: 67,
        title: "Vari Nighali Pandhari",
        image: "/drawings/67_Vari_nighali_pandhari.jpg",
    },
    {
        id: 68,
        title: "Bappa, Buffed",
        image: "/drawings/68_Ganpati_Bappa_morya.jpg",
        isFeatured: true,
        featuredOrder: 8,
        thoughts: "The best drawing I think I have ever made. Ganpati Bappa, but not the gentle serene version. This one is powerful. Every muscle deliberate. I wanted to draw divinity the way strength actually feels.",
    },
    {
        id: 69,
        title: "The One-Eyebrow Look",
        image: "/drawings/69_Self_Portrait.jpg",
        isFeatured: true,
        featuredOrder: 21,
        thoughts: "Late 2025. One eye steady, one brow raised. Lost in love, sure. But somewhere along the way I built something. I coded, I shipped, I grew. This is me looking back at all of it and deciding I'm not too bad after all.",
    },
    {
        id: 70,
        title: "Infinity Castle",
        image: "/drawings/70_Infinity_Castle.jpg",
        isFeatured: true,
        featuredOrder: 10,
        thoughts: "Early 2024. I was deep into Demon Slayer. The Infinity Castle obsessed me. The geometry, the impossible angles, the sense of falling forever. I spent a long time on the details. Tanjiro mid-fall, corridors going nowhere.",
    },
    {
        id: 71,
        title: "Her Eyes",
        image: "/drawings/71_Her_Eyes.jpg",
        isFeatured: true,
        featuredOrder: 1,
        thoughts: "This is where it started. A close-up of the eyes that made me fall in love. The glow, the warmth, the way they held something I couldn't name. I still remember the exact moment I first saw them. This drawing is that moment. Everything else in this collection exists in the shadow of this one.",
    },
    {
        id: 72,
        title: "Kanheri, in Warli",
        image: "/drawings/72_Kanheri_Warli_Cave_Painting.jpg",
        isFeatured: true,
        featuredOrder: 9,
        thoughts: "The Kanheri caves in Sanjay Gandhi National Park, drawn in the style of Warli. Trees, pillars, floors, walls, all in that ancient tribal language of lines. The image you see here is inverted. The original was black on white, but the negative feels more honest. Like looking at a photograph of something that happened a long time ago.",
    },
    {
        id: 73,
        title: "Krishna Lifts Govardhan",
        image: "/drawings/73_Govardhan_Parvat.jpg",
        isFeatured: true,
        featuredOrder: 13,
        thoughts: "Madhubani style. A folk art language that turns myth into geometry. Krishna lifting an entire mountain. The style demanded patience; every fill, every border had its own rhythm.",
    },
    {
        id: 74,
        title: "Vasudev",
        image: "/drawings/74_Vasu_Dev.jpg",
        isFeatured: true,
        featuredOrder: 14,
        thoughts: "Made for Maharashtra Din. Vasudev, the wandering folk performer, bells in hand, a living tradition. Something about drawing him felt like an act of preservation.",
    },
    {
        id: 75,
        title: "Shivaji Maharaj",
        image: "/drawings/75_Shivaji_Maharaj.jpg",
        isFeatured: true,
        featuredOrder: 20,
        thoughts: "A portrait on a hundred. Chhatrapati Shivaji Maharaj deserved more than a quick sketch. I wanted to get the weight of him right, the sharpness in the eyes, the quiet authority. Some subjects demand your full attention. This was one of them.",
    },
    {
        id: 76,
        title: "The Split",
        image: "/drawings/76_Split.jpg",
        isFeatured: true,
        featuredOrder: 5,
        thoughts: "The world sees me as a machine. Rigid, black and white, functional. But beneath the dark shell, the colors never stopped flowing. This is the line between who they see and who I actually am.",
    },
];

export default artPieces;